suite: test configmap

templates:
  - configmap.yaml

tests:
  - it: should have postgres environments when postgres is enabled
    set:
      backendStore.postgres.enabled: true
      backendStore.postgres.host: postgres-service
      backendStore.postgres.port: 5432
      backendStore.postgres.database: postgres
    asserts:
      - hasDocuments:
          count: 1
      - equal:
          path: data.PGHOST
          value: postgres-service
      - equal:
          path: data.PGPORT
          value: "5432"
      - equal:
          path: data.PGDATABASE
          value: postgres

  - it: should have postgres environments and migration configmaps when postgres and migration are enabled
    set:
      backendStore.postgres.enabled: true
      backendStore.postgres.host: postgres-service
      backendStore.postgres.port: 5432
      backendStore.postgres.database: postgres
      backendStore.databaseMigration: true
    asserts:
      - hasDocuments:
          count: 2

  - it: should match snapshot of default values
    release:
      name: mlflow
      namespace: mlflow
    chart:
      version: 1.0.0
      appVersion: 1.0.0
    asserts:
      - matchSnapshot: { }
